# TODO: Make pre-commit.nix instead?
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path backend/Cargo.toml --check
        language: system
        pass_filenames: false
        types: [rust]
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --manifest-path backend/Cargo.toml --all-targets
        language: system
        pass_filenames: false
        types: [rust]
